### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by greensopinion** [talamaska/onboarding_overlay#32]
I've been seeing the following in my error reports, not sure on reproduction steps since I haven't been able to reproduce it locally.

```
Null check operator used on a null value
_CastError
#0      RenderBox.size (package:flutter/src/rendering/box.dart:2004)
#1      _OnboardingStepperState.calcWidgetRect (package:onboarding_overlay/src/stepper.dart:206)
#2      _OnboardingStepperState.build.<anonymous closure> (package:onboarding_overlay/src/stepper.dart:310)
#3      _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:122)
#4      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2600)
#5      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:156)
#6      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1997)
#7      BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2519)
#8      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1997)
#9      RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:230)
#10     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:319)
#11     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1731)
#12     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887)
#13     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497)
#14     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883)
#15     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363)
#16     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144)
#17     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081)
#18     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995)
#19     _rootRun (dart:async/zone.dart:1426)
#20     _CustomZone.run (dart:async/zone.dart:1328)
#21     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#22     _invoke (dart:ui/hooks.dart:151)
#23     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308)
#24     _drawFrame (dart:ui/hooks.dart:115)
```

**Comment by talamaska** [comment]
Thanks for the report. Will look into this.

**Comment by talamaska** [comment]
@greensopinion what version of the library your are using?
